title: Pinnacles Analytics
theme: jekyll-theme-slate  
color_scheme: light
permalink: pretty

# Optional links in top-right nav
aux_links:
  "Pricing":
    - "/pricing.html"
  "Case Studies":
    - "/case-study.html"
  "Contact":
    - "/contact.html"
